### ISSUE TITLE
Futur must occur at the beginning of the file

### ISSUE THREAD

**Issue by voXrey** [EMACC99/mangadex#12]
**Description**
When I import mangadex I have this error : 
`SyntaxError: from __future__ imports must occur at the beginning of the file`

**Screenshot**
![image](https://user-images.githubusercontent.com/72698969/150538428-3ff5bcd0-0b33-4454-8a19-d7dc2b44232f.png)

**Desktop**
 - OS: windows11
 - Python: 3.9
 - Mangadex version: 2.5.1

**Origin of the problem**
in mangadex/api.py
Line 4 -> __future__ imports must be before all code-relevant lines

**A solution**
Replace this line to first file's line like this:
![image](https://user-images.githubusercontent.com/72698969/150539333-ba920795-4ae1-4fe5-a0e5-95c60fcdf8ff.png)

**Comment by EMACC99** [comment]
thanks for bringing this up, for some reason it didn't show on my testing. I will fix it right away. If you find any other thing or want to implement something feel free to make a pull request

**Comment by voXrey** [comment]
You're welcome, it's noted 👍
