### ISSUE TITLE
Module import failing due to SyntaxError

### ISSUE THREAD

**Issue by RealStickman** [EMACC99/mangadex#13]
When using `import mangadex` in python, the import fails due to a syntax error.  

Python version: 3.10.2  

**To Reproduce**
1. Enter python shell
2. `import mangadex`

**Expected behavior**
The import should work

**Traceback**
```
>>> import mangadex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marc/.local/lib/python3.10/site-packages/mangadex/__init__.py", line 8, in <module>
    from .api import (Api)
  File "/home/marc/.local/lib/python3.10/site-packages/mangadex/api.py", line 4
    from __future__ import absolute_import
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: from __future__ imports must occur at the beginning of the file
```

**Solution**
Move the line `from __future__ import absolute_import` above `import re` in `api.py`  
```
"""
"""
from __future__ import absolute_import
import re #for validating email and prevent spam
...
```

**Comment by EMACC99** [comment]
Hey, I've now tracked the issue with this, and turns out I didn't push the fix to the PyPI (this issue was noticed before), this was an oversight on my part. Thanks for letting me know.

**Comment by RealStickman** [comment]
No problem, thanks for pushing the fix so quickly.

**Comment by EMACC99** [comment]
Thanks to you for bringing this up. If you find more issues o want to implement something, feel free to make a PR.
