### ISSUE TITLE
"AttributeError: 'NoneType' object has no attribute 'keys'" when trying to get chapters

### ISSUE THREAD

**Issue by pepoboyii** [EMACC99/mangadex#2]
When I use `chapter = api.get_chapter(id = "d86cf65b-5f6c-437d-a0af-19a31f94ec55")` I get the error in the title.

This error occurs in the file "url_models.py" in line 89: `if "result" in str(data.keys()):`

I expected a list of chapters. This occurred in Windows 10, when making a file in Visual Studio Code.

**Comment by EMACC99** [comment]
Doing a little debugging it shows that there is a 404 response from the site. Can you tell me how did you get the Chapter Id?

**Comment by pepoboyii** [comment]
Oh well look at me. I input the chapter id incorrectly. Please accept my humble apologies for wasting your time.

**Comment by EMACC99** [comment]
It's ok, this made me realise that I need to put more information in the custom error classes that are raised in the code
