### ISSUE TITLE
Cannot use the login function

### ISSUE THREAD

**Issue by john-erinjery** [EMACC99/mangadex#26]
I wanted to fetch my reading list from my mangadex account, so I tried using the Api().login() method. However, no matter how many times I do it or how many times I confirm my username and password, I got this traceback : 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Programing\python-web\env\Lib\site-packages\mangadex\api.py", line 539, in login
    self.__auth_handler(json_payload= {"username" : username, "password" : password})
  File "C:\Programing\python-web\env\Lib\site-packages\mangadex\api.py", line 14, in __auth_handler
    auth = URLRequest.request_url(url, "POST", params = json_payload, timeout=self.timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Programing\python-web\env\Lib\site-packages\mangadex\url_models.py", line 59, in request_url
    raise ApiError(resp)
          ^^^^^^^^^^^^^^
  File "C:\Programing\python-web\env\Lib\site-packages\mangadex\errors.py", line 15, in __init__
    self.details = self.resp.text["detail"]
                   ~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

I tried using the official api using this code : 

```
>>> import requests
>>> data = {'username' : ' ---', 'password' : '----'}
>>> url = "https://api.mangadex.org/auth/login"
>>> r = requests.post(url, json=data)
>>> r.json()
{'result': 'error', 'errors': [{'id': '70289a8c-eed8-5c0e-989b-4c73c13bf791', 'status': 401, 'title': 'unauthorized_http_exception', 'detail': 'User / Password does not match', 'context': None}]}
```

as you can see there's that error. so i figured it was a problem with the official api, am i correct?
and if It <i>is</is> a problem with the official api, is there any other way of getting my reading lists?

**Comment by EMACC99** [comment]
Hello, seems that the current method for login has been deprecated, and we need to migrate to the new OAuth2 login system. I will investigate further how to implement it. For getting the reading lists, unfortunately, there is no way to get a user's manga library without being on a public reading list.

**Comment by EMACC99** [comment]
Hello again, can you retry the login? As I was debugging I couldn't replicate the issue (the migration to OAuth will still happen) as the endpoint seems to be up still. Can you include which version of the library you are using?

**Comment by john-erinjery** [comment]
I confirmed the error is still present, and i tried to login with another account only to get the same result.
Ahh for additional info, I <i>did</i> try asking in the mangadex forum on reddit and this is the info I got : 

![image](https://user-images.githubusercontent.com/91457967/231074796-1acec486-2aa4-4854-9130-012e07d47927.png)

here's the [link](https://www.reddit.com/r/mangadex/comments/12dilc7/is_the_authentication_endpoints_in_the_mangadex/) to the discussion

**Comment by MrSoupman** [comment]
Hi, I found this on the MangaDex discord:
![image](https://user-images.githubusercontent.com/6711246/233822584-8bde2e24-959c-438f-a03b-4c620f4b1717.png)
That might answer your question, and might be why it wasn't repeatable during debugging.

**Comment by john-erinjery** [comment]
Oh so that was the reason huh. Thanks a lot for that! I figured out how to login with the bearer text but it was pretty inefficient, and using selenium is gonna make my program a lot slower and bulkier...guess I'll wait for OAuth to be implemented. It ain't implemented yet right? Where can I find out if it got implemented?

**Comment by EMACC99** [comment]
Sorry for the very late response, I've been attending some IRL matters and couldn't dedicate much time to the followup in this issue.

I came across a quite old announcement in the discord server that the oauth is still in the dev phase, however, I'm not sure if this contains up to date user data as from my understanding is just for testing the integration

<img width="847" alt="image" src="https://github.com/EMACC99/mangadex/assets/50022572/e42e2b80-c83e-4b66-a1b9-6a4134f122d7">

(yes, I use discord in light mode, sorry if it burned your eyes)


As you saw in your investigation, there is not a way to register a third-party client right now so our only hope is that the .dev has everything we need for the new account authentications, but I'm not sure about the reliability of using it for every login or just using it for the accounts that are in a case similar to yours. If anyone have an idea on how to approach this, you're more than welcome to share it.

**Comment by lasersPew** [comment]
They have added it to the production server. Note: See #32. 

In the changes in that code and in the spec, it says that it needs to have client id and client secret after you created an app in the API clients in the settings though it will work for **the accounts that created the apps themselves**.

After some testing with this code:
```py
username = #redacted
password = #redacted
clientId = #redacted
clientSecret = #redacted

resp = requests.post(url, data = {"grant_type": "password",  "username": username,  "password": password, "client_id" : clientId, "client_secret" : clientSecret})

resp = resp.json()
```

It spits out token type, scope, and client type (useful when public clients are implemented) and the access and refresh token among other things.
