### ISSUE TITLE
Account

### ISSUE THREAD

**Issue by WSrujan** [EMACC99/mangadex#3]
Does it supports account creation?

**Comment by EMACC99** [comment]
Not yet, as I've been working on some error handling as well as polishing other things. But I think I will start implementing this

**Comment by EMACC99** [comment]
The account creation is now completed but account recovery needs some testing, if you experience problems with those methods please let me know

**Comment by WSrujan** [comment]
error in line 943
![image](https://user-images.githubusercontent.com/49693115/120434938-b260cb80-c39a-11eb-996c-d8c7ce726a24.png)

**Comment by EMACC99** [comment]
I already fixed the thing with the regex, it was a mistake on my part. Doing some research, turns out that account creation thru the API is not fully supported (that's why it return error 412) and it's recommended to wait for the front end to be ready to make and account.

**Comment by lasersPew** [comment]
I would like to notify that the account creation won't be functional for good.

More info: 
![image](https://github.com/EMACC99/mangadex/assets/87552756/e284d3cc-9cee-4923-b3ac-e4b0e9f1eb78)
