### ISSUE TITLE
'basestring' is not defined', 'No module named 'past'

### ISSUE THREAD

**Issue by TLaks** [EMACC99/mangadex#4]
Getting an error when I try and import the module. Windows 10

Instead of being able to import, these errors came up. I'm getting various module errors when I try and import the mangadex module. When I install one module, another error with a different module comes up

![image](https://user-images.githubusercontent.com/85596062/121280960-20c6f180-c8a5-11eb-8869-c4a10c2a0394.png)
![image](https://user-images.githubusercontent.com/85596062/121281002-35a38500-c8a5-11eb-88e4-24c2f3cec30c.png)
![image](https://user-images.githubusercontent.com/85596062/121281868-a008f500-c8a6-11eb-967f-fcda9406fc08.png)

**Comment by EMACC99** [comment]
To solve this you need to install the `dateutil` module. To install it you need to run `pip install python-dateutil`. This was an oversight on my side to not put the `dateutil` and `future` modules in the `setup.py`

**Comment by TLaks** [comment]
Yep, thanks for that
